// <auto-generated />
using System;
using Inversor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inversor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260725135302_AddLinkBidirectionalTrace")]
    partial class AddLinkBidirectionalTrace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inversor.Core.Domain.Entities.GrammarTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MacroTagId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TheoryDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("MacroTagId");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("GrammarTopics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_general_error",
                            TheoryDescription = "Válvula de escape",
                            Title = "Error ortográfico general"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_spelling_mistake",
                            TheoryDescription = "",
                            Title = "Error de deletreo/escritura"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_capitalization_missing",
                            TheoryDescription = "",
                            Title = "Falta mayúscula"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_capitalization_unnecessary",
                            TheoryDescription = "",
                            Title = "Mayúscula innecesaria"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_punctuation_missing",
                            TheoryDescription = "",
                            Title = "Signo de puntuación faltante"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_punctuation_incorrect",
                            TheoryDescription = "",
                            Title = "Signo de puntuación incorrecto"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_accentuation_missing",
                            TheoryDescription = "",
                            Title = "Falta de acento/tilde"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_accentuation_incorrect",
                            TheoryDescription = "",
                            Title = "Acento/tilde incorrecto"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_hyphenation_error",
                            TheoryDescription = "",
                            Title = "Error en uso de guion"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_apostrophe_missing",
                            TheoryDescription = "",
                            Title = "Apóstrofo faltante"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_apostrophe_misused",
                            TheoryDescription = "",
                            Title = "Apóstrofo mal usado"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_abbreviation_error",
                            TheoryDescription = "",
                            Title = "Error de abreviatura"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_contraction_error",
                            TheoryDescription = "",
                            Title = "Error en contracción"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_spacing_error",
                            TheoryDescription = "",
                            Title = "Error de espaciado"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            MacroTagId = new Guid("11111111-1111-1111-1111-100000000000"),
                            Tag = "orthography_symbol_misused",
                            TheoryDescription = "",
                            Title = "Uso incorrecto de símbolo"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_general_error",
                            TheoryDescription = "Válvula de escape",
                            Title = "Error morfológico general"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_verb_conjugation",
                            TheoryDescription = "",
                            Title = "Conjugación verbal incorrecta"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_verb_tense_wrong",
                            TheoryDescription = "",
                            Title = "Tiempo verbal incorrecto"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_verb_infinitive_needed",
                            TheoryDescription = "",
                            Title = "Se requiere verbo en infinitivo"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_verb_gerund_needed",
                            TheoryDescription = "",
                            Title = "Se requiere gerundio/participio presente"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_verb_participle_needed",
                            TheoryDescription = "",
                            Title = "Se requiere participio pasado"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_verb_irregular_error",
                            TheoryDescription = "",
                            Title = "Error en verbo irregular"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_noun_pluralization",
                            TheoryDescription = "",
                            Title = "Error de pluralización"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_noun_gender_agreement",
                            TheoryDescription = "",
                            Title = "Error de concordancia de género"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_noun_number_agreement",
                            TheoryDescription = "",
                            Title = "Error de concordancia de número"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_adjective_agreement",
                            TheoryDescription = "",
                            Title = "Concordancia de adjetivo incorrecta"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_adjective_comparative",
                            TheoryDescription = "",
                            Title = "Error en forma comparativa"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_adjective_superlative",
                            TheoryDescription = "",
                            Title = "Error en forma superlativa"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_adverb_formation",
                            TheoryDescription = "",
                            Title = "Formación incorrecta del adverbio"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_pronoun_case_error",
                            TheoryDescription = "",
                            Title = "Error de caso en pronombre (ej. me vs I)"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000016"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_pronoun_reflexive_error",
                            TheoryDescription = "",
                            Title = "Error en pronombre reflexivo"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000017"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_pronoun_possessive_error",
                            TheoryDescription = "",
                            Title = "Error en pronombre posesivo"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000018"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_article_definite_missing",
                            TheoryDescription = "",
                            Title = "Falta artículo definido"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000019"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_article_indefinite_missing",
                            TheoryDescription = "",
                            Title = "Falta artículo indefinido"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_article_unnecessary",
                            TheoryDescription = "",
                            Title = "Uso innecesario de artículo"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000021"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_preposition_wrong_form",
                            TheoryDescription = "",
                            Title = "Forma incorrecta de preposición"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000022"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_prefix_error",
                            TheoryDescription = "",
                            Title = "Error en prefijo"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000023"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_suffix_error",
                            TheoryDescription = "",
                            Title = "Error en sufijo"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000024"),
                            MacroTagId = new Guid("22222222-2222-2222-2222-200000000000"),
                            Tag = "morphology_word_class_confusion",
                            TheoryDescription = "",
                            Title = "Confusión de categoría gramatical (ej. usar adjetivo como verbo)"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_general_error",
                            TheoryDescription = "Válvula de escape",
                            Title = "Error sintáctico general"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_word_order_subject_verb",
                            TheoryDescription = "",
                            Title = "Orden incorrecto de sujeto y verbo"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_word_order_adjective_noun",
                            TheoryDescription = "",
                            Title = "Orden incorrecto de adjetivo y sustantivo"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_word_order_adverb",
                            TheoryDescription = "",
                            Title = "Posición incorrecta del adverbio"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_word_order_question",
                            TheoryDescription = "",
                            Title = "Estructura incorrecta de pregunta"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_word_order_negation",
                            TheoryDescription = "",
                            Title = "Estructura incorrecta de negación"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_subject_missing",
                            TheoryDescription = "",
                            Title = "Sujeto omitido/faltante"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_subject_unnecessary",
                            TheoryDescription = "",
                            Title = "Sujeto redundante"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_verb_missing",
                            TheoryDescription = "",
                            Title = "Verbo principal faltante"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_auxiliary_verb_missing",
                            TheoryDescription = "",
                            Title = "Verbo auxiliar faltante"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_auxiliary_verb_unnecessary",
                            TheoryDescription = "",
                            Title = "Verbo auxiliar innecesario"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000012"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_object_missing",
                            TheoryDescription = "",
                            Title = "Objeto directo/indirecto faltante"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000013"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_object_position",
                            TheoryDescription = "",
                            Title = "Posición incorrecta del objeto"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000014"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_preposition_missing",
                            TheoryDescription = "",
                            Title = "Preposición faltante"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000015"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_preposition_unnecessary",
                            TheoryDescription = "",
                            Title = "Preposición innecesaria"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000016"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_preposition_stranded",
                            TheoryDescription = "",
                            Title = "Preposición mal posicionada al final"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000017"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_conjunction_missing",
                            TheoryDescription = "",
                            Title = "Conjunción faltante"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000018"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_conjunction_misused",
                            TheoryDescription = "",
                            Title = "Conjunción mal utilizada"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000019"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_clause_dependent_error",
                            TheoryDescription = "",
                            Title = "Error en cláusula subordinada/dependiente"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000020"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_clause_relative_error",
                            TheoryDescription = "",
                            Title = "Error en cláusula relativa"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000021"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_conditional_structure",
                            TheoryDescription = "",
                            Title = "Estructura de condicional incorrecta"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000022"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_passive_voice_error",
                            TheoryDescription = "",
                            Title = "Error en estructura de voz pasiva"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000023"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_reported_speech_error",
                            TheoryDescription = "",
                            Title = "Error en estilo indirecto"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000024"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_double_negative",
                            TheoryDescription = "",
                            Title = "Doble negación no permitida"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000025"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_parallelism_error",
                            TheoryDescription = "",
                            Title = "Falta de paralelismo estructural"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000026"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_run_on_sentence",
                            TheoryDescription = "",
                            Title = "Oración continua sin separación (Run-on)"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000027"),
                            MacroTagId = new Guid("33333333-3333-3333-3333-300000000000"),
                            Tag = "syntax_fragment_sentence",
                            TheoryDescription = "",
                            Title = "Oración fragmentada/incompleta"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_general_error",
                            TheoryDescription = "Válvula de escape",
                            Title = "Error léxico general"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_vocabulary_wrong_word",
                            TheoryDescription = "",
                            Title = "Palabra incorrecta para el contexto"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_vocabulary_false_friend",
                            TheoryDescription = "",
                            Title = "Falso amigo (interferencia de idioma nativo)"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_vocabulary_invented_word",
                            TheoryDescription = "",
                            Title = "Palabra inexistente/inventada"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_verb_collocation",
                            TheoryDescription = "",
                            Title = "Colocación verbal incorrecta (ej. make vs do)"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_noun_collocation",
                            TheoryDescription = "",
                            Title = "Colocación de sustantivo incorrecta"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000007"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_adjective_collocation",
                            TheoryDescription = "",
                            Title = "Colocación de adjetivo incorrecta"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000008"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_preposition_choice",
                            TheoryDescription = "",
                            Title = "Elección incorrecta de preposición"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000009"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_phrasal_verb_choice",
                            TheoryDescription = "",
                            Title = "Verbo preposicional/compuesto incorrecto"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000010"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_idiom_misused",
                            TheoryDescription = "",
                            Title = "Uso incorrecto de modismo/frase hecha"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000011"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_idiom_literal_translation",
                            TheoryDescription = "",
                            Title = "Traducción literal de modismo"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000012"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_register_too_formal",
                            TheoryDescription = "",
                            Title = "Vocabulario demasiado formal"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000013"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_register_too_informal",
                            TheoryDescription = "",
                            Title = "Vocabulario demasiado informal"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000014"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_slang_misused",
                            TheoryDescription = "",
                            Title = "Uso incorrecto de jerga/slang"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000015"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_repetition_redundancy",
                            TheoryDescription = "",
                            Title = "Repetición innecesaria de vocabulario"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000016"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_transition_word_choice",
                            TheoryDescription = "",
                            Title = "Conector lógico mal seleccionado"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000017"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_quantifier_choice",
                            TheoryDescription = "",
                            Title = "Cuantificador incorrecto (ej. much vs many)"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000018"),
                            MacroTagId = new Guid("44444444-4444-4444-4444-400000000000"),
                            Tag = "lexicon_determiner_choice",
                            TheoryDescription = "",
                            Title = "Determinante incorrecto (ej. this vs that)"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            MacroTagId = new Guid("55555555-5555-5555-5555-500000000000"),
                            Tag = "semantics_general_error",
                            TheoryDescription = "Válvula de escape",
                            Title = "Error semántico general"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            MacroTagId = new Guid("55555555-5555-5555-5555-500000000000"),
                            Tag = "semantics_ambiguous_meaning",
                            TheoryDescription = "",
                            Title = "Significado ambiguo o poco claro"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            MacroTagId = new Guid("55555555-5555-5555-5555-500000000000"),
                            Tag = "semantics_illogical_statement",
                            TheoryDescription = "",
                            Title = "Declaración ilógica o contradictoria"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            MacroTagId = new Guid("55555555-5555-5555-5555-500000000000"),
                            Tag = "semantics_literal_translation_error",
                            TheoryDescription = "",
                            Title = "Traducción literal que pierde sentido"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            MacroTagId = new Guid("55555555-5555-5555-5555-500000000000"),
                            Tag = "semantics_redundancy",
                            TheoryDescription = "",
                            Title = "Redundancia semántica (pleonasmo)"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            MacroTagId = new Guid("55555555-5555-5555-5555-500000000000"),
                            Tag = "semantics_nuance_lost",
                            TheoryDescription = "",
                            Title = "Pérdida de matiz o tono sutil"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000007"),
                            MacroTagId = new Guid("55555555-5555-5555-5555-500000000000"),
                            Tag = "semantics_scope_ambiguity",
                            TheoryDescription = "",
                            Title = "Ambigüedad de alcance (ej. negación)"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000008"),
                            MacroTagId = new Guid("55555555-5555-5555-5555-500000000000"),
                            Tag = "semantics_idiomatic_meaning_lost",
                            TheoryDescription = "",
                            Title = "Pérdida de significado idiomático"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000009"),
                            MacroTagId = new Guid("55555555-5555-5555-5555-500000000000"),
                            Tag = "semantics_reference_unclear",
                            TheoryDescription = "",
                            Title = "Referente de pronombre poco claro"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            MacroTagId = new Guid("66666666-6666-6666-6666-600000000000"),
                            Tag = "pragmatics_general_error",
                            TheoryDescription = "Válvula de escape",
                            Title = "Error pragmático general"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            MacroTagId = new Guid("66666666-6666-6666-6666-600000000000"),
                            Tag = "pragmatics_impolite_tone",
                            TheoryDescription = "",
                            Title = "Tono descortés o muy directo"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            MacroTagId = new Guid("66666666-6666-6666-6666-600000000000"),
                            Tag = "pragmatics_overly_polite",
                            TheoryDescription = "",
                            Title = "Tono excesivamente cortés para el contexto"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            MacroTagId = new Guid("66666666-6666-6666-6666-600000000000"),
                            Tag = "pragmatics_inappropriate_register",
                            TheoryDescription = "",
                            Title = "Registro inapropiado para la situación social"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            MacroTagId = new Guid("66666666-6666-6666-6666-600000000000"),
                            Tag = "pragmatics_cultural_misunderstanding",
                            TheoryDescription = "",
                            Title = "Malentendido o tabú cultural"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000006"),
                            MacroTagId = new Guid("66666666-6666-6666-6666-600000000000"),
                            Tag = "pragmatics_indirectness_missing",
                            TheoryDescription = "",
                            Title = "Falta de tacto/mitigación en una petición"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000007"),
                            MacroTagId = new Guid("66666666-6666-6666-6666-600000000000"),
                            Tag = "pragmatics_response_unnatural",
                            TheoryDescription = "",
                            Title = "Respuesta gramatical pero antinatural"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000008"),
                            MacroTagId = new Guid("66666666-6666-6666-6666-600000000000"),
                            Tag = "pragmatics_greeting_inappropriate",
                            TheoryDescription = "",
                            Title = "Saludo inapropiado"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000009"),
                            MacroTagId = new Guid("66666666-6666-6666-6666-600000000000"),
                            Tag = "pragmatics_closing_inappropriate",
                            TheoryDescription = "",
                            Title = "Despedida inapropiada"
                        });
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.MacroTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("MacroTags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-100000000000"),
                            Description = "Escritura correcta de las palabras.",
                            Tag = "ORTHOGRAPHY"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-200000000000"),
                            Description = "Forma y conjugación de las palabras.",
                            Tag = "MORPHOLOGY"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-300000000000"),
                            Description = "Orden y estructura de la oración.",
                            Tag = "SYNTAX"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-400000000000"),
                            Description = "Vocabulario y significado literal.",
                            Tag = "LEXICON"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-500000000000"),
                            Description = "Sentido lógico de la oración.",
                            Tag = "SEMANTICS"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-600000000000"),
                            Description = "Uso adecuado según el contexto.",
                            Tag = "PRAGMATICS"
                        });
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.SubmitTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BriefExplanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectedFragment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GrammarTopicId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsError")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFragment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TranslationSubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrammarTopicId");

                    b.HasIndex("TranslationSubmissionId");

                    b.ToTable("SubmitTags");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.TopicMastery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveSuccesses")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentIntervalDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("EasinessFactor")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<Guid>("GrammarTopicId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MasteryScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("NextReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserLanguageProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrammarTopicId");

                    b.HasIndex("UserLanguageProfileId");

                    b.ToTable("TopicMasteries");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.TranslationSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectedOutput")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GeneralFeedback")
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OriginalInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TraceId")
                        .HasColumnType("text");

                    b.Property<Guid>("UserLanguageProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserLanguageProfileId");

                    b.ToTable("TranslationSubmissions", (string)null);
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.UserLanguageProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssessedLevel")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("DailyRequestCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastRequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LearnLanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NativeLanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLanguageProfiles");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.HasIndex("BusName", "Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.GrammarTopic", b =>
                {
                    b.HasOne("Inversor.Core.Domain.Entities.MacroTag", "MacroTag")
                        .WithMany("GrammarTopics")
                        .HasForeignKey("MacroTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MacroTag");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.SubmitTag", b =>
                {
                    b.HasOne("Inversor.Core.Domain.Entities.GrammarTopic", "GrammarTopic")
                        .WithMany()
                        .HasForeignKey("GrammarTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inversor.Core.Domain.Entities.TranslationSubmission", "TranslationSubmission")
                        .WithMany("SubmitTags")
                        .HasForeignKey("TranslationSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrammarTopic");

                    b.Navigation("TranslationSubmission");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.TopicMastery", b =>
                {
                    b.HasOne("Inversor.Core.Domain.Entities.GrammarTopic", "GrammarTopic")
                        .WithMany()
                        .HasForeignKey("GrammarTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inversor.Core.Domain.Entities.UserLanguageProfile", "UserLanguageProfile")
                        .WithMany("TopicMasteries")
                        .HasForeignKey("UserLanguageProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrammarTopic");

                    b.Navigation("UserLanguageProfile");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.TranslationSubmission", b =>
                {
                    b.HasOne("Inversor.Core.Domain.Entities.UserLanguageProfile", "UserLanguageProfile")
                        .WithMany("Submissions")
                        .HasForeignKey("UserLanguageProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserLanguageProfile");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.UserLanguageProfile", b =>
                {
                    b.HasOne("Inversor.Core.Domain.Entities.User", "User")
                        .WithMany("LanguageProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.MacroTag", b =>
                {
                    b.Navigation("GrammarTopics");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.TranslationSubmission", b =>
                {
                    b.Navigation("SubmitTags");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("LanguageProfiles");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.UserLanguageProfile", b =>
                {
                    b.Navigation("Submissions");

                    b.Navigation("TopicMasteries");
                });
#pragma warning restore 612, 618
        }
    }
}
