// <auto-generated />
using System;
using Inversor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inversor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260718131146_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inversor.Core.Domain.Entities.GrammarTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MacroTagId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TheoryDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("MacroTagId");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("GrammarTopics");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.MacroTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("MacroTags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-100000000000"),
                            Description = "Escritura correcta de las palabras.",
                            Tag = "ORTHOGRAPHY"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-200000000000"),
                            Description = "Forma y conjugación de las palabras.",
                            Tag = "MORPHOLOGY"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-300000000000"),
                            Description = "Orden y estructura de la oración.",
                            Tag = "SYNTAX"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-400000000000"),
                            Description = "Vocabulario y significado literal.",
                            Tag = "LEXICON"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-500000000000"),
                            Description = "Sentido lógico de la oración.",
                            Tag = "SEMANTICS"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-600000000000"),
                            Description = "Uso adecuado según el contexto.",
                            Tag = "PRAGMATICS"
                        });
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.SubmitTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BriefExplanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectedFragment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GrammarTopicId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsError")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFragment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TranslationSubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrammarTopicId");

                    b.HasIndex("TranslationSubmissionId");

                    b.ToTable("SubmitTags");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.TopicMastery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveSuccesses")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentIntervalDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("EasinessFactor")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<Guid>("GrammarTopicId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MasteryScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("NextReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserLanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrammarTopicId");

                    b.HasIndex("UserLanguageId");

                    b.ToTable("TopicMasteries");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.TranslationSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneralFeedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserLanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserLanguageProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserLanguageProfileId");

                    b.ToTable("TranslationSubmissions");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.UserLanguageProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssessedLevel")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("DailyRequestCount")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("LastRequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLanguageProfiles");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.GrammarTopic", b =>
                {
                    b.HasOne("Inversor.Core.Domain.Entities.MacroTag", "MacroTag")
                        .WithMany("GrammarTopics")
                        .HasForeignKey("MacroTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MacroTag");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.SubmitTag", b =>
                {
                    b.HasOne("Inversor.Core.Domain.Entities.GrammarTopic", "GrammarTopic")
                        .WithMany()
                        .HasForeignKey("GrammarTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inversor.Core.Domain.Entities.TranslationSubmission", "TranslationSubmission")
                        .WithMany("SubmitTags")
                        .HasForeignKey("TranslationSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrammarTopic");

                    b.Navigation("TranslationSubmission");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.TopicMastery", b =>
                {
                    b.HasOne("Inversor.Core.Domain.Entities.GrammarTopic", "GrammarTopic")
                        .WithMany()
                        .HasForeignKey("GrammarTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inversor.Core.Domain.Entities.UserLanguageProfile", "UserLanguage")
                        .WithMany("TopicMasteries")
                        .HasForeignKey("UserLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrammarTopic");

                    b.Navigation("UserLanguage");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.TranslationSubmission", b =>
                {
                    b.HasOne("Inversor.Core.Domain.Entities.UserLanguageProfile", "UserLanguageProfile")
                        .WithMany("Submissions")
                        .HasForeignKey("UserLanguageProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserLanguageProfile");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.UserLanguageProfile", b =>
                {
                    b.HasOne("Inversor.Core.Domain.Entities.User", "User")
                        .WithMany("LanguageProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.MacroTag", b =>
                {
                    b.Navigation("GrammarTopics");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.TranslationSubmission", b =>
                {
                    b.Navigation("SubmitTags");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("LanguageProfiles");
                });

            modelBuilder.Entity("Inversor.Core.Domain.Entities.UserLanguageProfile", b =>
                {
                    b.Navigation("Submissions");

                    b.Navigation("TopicMasteries");
                });
#pragma warning restore 612, 618
        }
    }
}
